//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IntemBB.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="testSoap", Namespace="http://tempuri.org/")]
    public partial class test : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Mesid_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecipe_nameDuoiOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_shiftOperationCompleted;
        
        private System.Threading.SendOrPostCallback Print_BBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Print_BB_AgainOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinishOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DieudongOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PrinterListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_BarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback mesidautoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Mesid_list_InlaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback MesidOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_mesidOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_mesid_recipe_weghtOperationCompleted;
        
        private System.Threading.SendOrPostCallback rubnodOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkTemVangOperationCompleted;
        
        private System.Threading.SendOrPostCallback insIF_Scan2MesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadPlanidOperationCompleted;
        
        private System.Threading.SendOrPostCallback ins_cantayOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_mes_pdayOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_barcode_if_scan2mesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_palletBBOperationCompleted;
        
        private System.Threading.SendOrPostCallback insIF_Scan2Mes_newOperationCompleted;
        
        private System.Threading.SendOrPostCallback ins_LRweighOperationCompleted;
        
        private System.Threading.SendOrPostCallback ins_IF_Scan2Mes_newOperationCompleted;
        
        private System.Threading.SendOrPostCallback sanluong_daquetOperationCompleted;
        
        private System.Threading.SendOrPostCallback sv_hoachatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public test() {
            this.Url = global::IntemBB.Properties.Settings.Default.IntemBB_WebReference_test;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event Get_Mesid_listCompletedEventHandler Get_Mesid_listCompleted;
        
        /// <remarks/>
        public event GetRecipe_nameDuoiCompletedEventHandler GetRecipe_nameDuoiCompleted;
        
        /// <remarks/>
        public event Get_shiftCompletedEventHandler Get_shiftCompleted;
        
        /// <remarks/>
        public event Print_BBCompletedEventHandler Print_BBCompleted;
        
        /// <remarks/>
        public event Print_BB_AgainCompletedEventHandler Print_BB_AgainCompleted;
        
        /// <remarks/>
        public event FinishCompletedEventHandler FinishCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event DieudongCompletedEventHandler DieudongCompleted;
        
        /// <remarks/>
        public event getBarcodeCompletedEventHandler getBarcodeCompleted;
        
        /// <remarks/>
        public event Get_PrinterListCompletedEventHandler Get_PrinterListCompleted;
        
        /// <remarks/>
        public event Get_BarcodeCompletedEventHandler Get_BarcodeCompleted;
        
        /// <remarks/>
        public event mesidautoCompletedEventHandler mesidautoCompleted;
        
        /// <remarks/>
        public event Get_Mesid_list_InlaiCompletedEventHandler Get_Mesid_list_InlaiCompleted;
        
        /// <remarks/>
        public event MesidCompletedEventHandler MesidCompleted;
        
        /// <remarks/>
        public event get_mesidCompletedEventHandler get_mesidCompleted;
        
        /// <remarks/>
        public event get_mesid_recipe_weghtCompletedEventHandler get_mesid_recipe_weghtCompleted;
        
        /// <remarks/>
        public event rubnodCompletedEventHandler rubnodCompleted;
        
        /// <remarks/>
        public event checkTemVangCompletedEventHandler checkTemVangCompleted;
        
        /// <remarks/>
        public event insIF_Scan2MesCompletedEventHandler insIF_Scan2MesCompleted;
        
        /// <remarks/>
        public event LoadPlanidCompletedEventHandler LoadPlanidCompleted;
        
        /// <remarks/>
        public event ins_cantayCompletedEventHandler ins_cantayCompleted;
        
        /// <remarks/>
        public event Check_mes_pdayCompletedEventHandler Check_mes_pdayCompleted;
        
        /// <remarks/>
        public event Check_barcode_if_scan2mesCompletedEventHandler Check_barcode_if_scan2mesCompleted;
        
        /// <remarks/>
        public event Check_palletBBCompletedEventHandler Check_palletBBCompleted;
        
        /// <remarks/>
        public event insIF_Scan2Mes_newCompletedEventHandler insIF_Scan2Mes_newCompleted;
        
        /// <remarks/>
        public event ins_LRweighCompletedEventHandler ins_LRweighCompleted;
        
        /// <remarks/>
        public event ins_IF_Scan2Mes_newCompletedEventHandler ins_IF_Scan2Mes_newCompleted;
        
        /// <remarks/>
        public event sanluong_daquetCompletedEventHandler sanluong_daquetCompleted;
        
        /// <remarks/>
        public event sv_hoachatCompletedEventHandler sv_hoachatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Login(string empno) {
            object[] results = this.Invoke("Login", new object[] {
                        empno});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string empno) {
            this.LoginAsync(empno, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string empno, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        empno}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Mesid_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Mesid_list(string Machno) {
            object[] results = this.Invoke("Get_Mesid_list", new object[] {
                        Machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Mesid_listAsync(string Machno) {
            this.Get_Mesid_listAsync(Machno, null);
        }
        
        /// <remarks/>
        public void Get_Mesid_listAsync(string Machno, object userState) {
            if ((this.Get_Mesid_listOperationCompleted == null)) {
                this.Get_Mesid_listOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Mesid_listOperationCompleted);
            }
            this.InvokeAsync("Get_Mesid_list", new object[] {
                        Machno}, this.Get_Mesid_listOperationCompleted, userState);
        }
        
        private void OnGet_Mesid_listOperationCompleted(object arg) {
            if ((this.Get_Mesid_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Mesid_listCompleted(this, new Get_Mesid_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecipe_nameDuoi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRecipe_nameDuoi(string Machno) {
            object[] results = this.Invoke("GetRecipe_nameDuoi", new object[] {
                        Machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecipe_nameDuoiAsync(string Machno) {
            this.GetRecipe_nameDuoiAsync(Machno, null);
        }
        
        /// <remarks/>
        public void GetRecipe_nameDuoiAsync(string Machno, object userState) {
            if ((this.GetRecipe_nameDuoiOperationCompleted == null)) {
                this.GetRecipe_nameDuoiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecipe_nameDuoiOperationCompleted);
            }
            this.InvokeAsync("GetRecipe_nameDuoi", new object[] {
                        Machno}, this.GetRecipe_nameDuoiOperationCompleted, userState);
        }
        
        private void OnGetRecipe_nameDuoiOperationCompleted(object arg) {
            if ((this.GetRecipe_nameDuoiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecipe_nameDuoiCompleted(this, new GetRecipe_nameDuoiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_shift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_shift() {
            object[] results = this.Invoke("Get_shift", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_shiftAsync() {
            this.Get_shiftAsync(null);
        }
        
        /// <remarks/>
        public void Get_shiftAsync(object userState) {
            if ((this.Get_shiftOperationCompleted == null)) {
                this.Get_shiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_shiftOperationCompleted);
            }
            this.InvokeAsync("Get_shift", new object[0], this.Get_shiftOperationCompleted, userState);
        }
        
        private void OnGet_shiftOperationCompleted(object arg) {
            if ((this.Get_shiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_shiftCompleted(this, new Get_shiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Print_BB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Print_BB(string tenkeo, string Machno, string printername, string ca, string usrno, string candao, string Soluong, string mesid, string pallet) {
            object[] results = this.Invoke("Print_BB", new object[] {
                        tenkeo,
                        Machno,
                        printername,
                        ca,
                        usrno,
                        candao,
                        Soluong,
                        mesid,
                        pallet});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Print_BBAsync(string tenkeo, string Machno, string printername, string ca, string usrno, string candao, string Soluong, string mesid, string pallet) {
            this.Print_BBAsync(tenkeo, Machno, printername, ca, usrno, candao, Soluong, mesid, pallet, null);
        }
        
        /// <remarks/>
        public void Print_BBAsync(string tenkeo, string Machno, string printername, string ca, string usrno, string candao, string Soluong, string mesid, string pallet, object userState) {
            if ((this.Print_BBOperationCompleted == null)) {
                this.Print_BBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrint_BBOperationCompleted);
            }
            this.InvokeAsync("Print_BB", new object[] {
                        tenkeo,
                        Machno,
                        printername,
                        ca,
                        usrno,
                        candao,
                        Soluong,
                        mesid,
                        pallet}, this.Print_BBOperationCompleted, userState);
        }
        
        private void OnPrint_BBOperationCompleted(object arg) {
            if ((this.Print_BBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Print_BBCompleted(this, new Print_BBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Print_BB_Again", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Print_BB_Again(string usrno, string Machno, string barcode, string mesid, string soluong, string printername, string tenkeo) {
            object[] results = this.Invoke("Print_BB_Again", new object[] {
                        usrno,
                        Machno,
                        barcode,
                        mesid,
                        soluong,
                        printername,
                        tenkeo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Print_BB_AgainAsync(string usrno, string Machno, string barcode, string mesid, string soluong, string printername, string tenkeo) {
            this.Print_BB_AgainAsync(usrno, Machno, barcode, mesid, soluong, printername, tenkeo, null);
        }
        
        /// <remarks/>
        public void Print_BB_AgainAsync(string usrno, string Machno, string barcode, string mesid, string soluong, string printername, string tenkeo, object userState) {
            if ((this.Print_BB_AgainOperationCompleted == null)) {
                this.Print_BB_AgainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrint_BB_AgainOperationCompleted);
            }
            this.InvokeAsync("Print_BB_Again", new object[] {
                        usrno,
                        Machno,
                        barcode,
                        mesid,
                        soluong,
                        printername,
                        tenkeo}, this.Print_BB_AgainOperationCompleted, userState);
        }
        
        private void OnPrint_BB_AgainOperationCompleted(object arg) {
            if ((this.Print_BB_AgainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Print_BB_AgainCompleted(this, new Print_BB_AgainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Finish", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Finish(string tenkeo, string mesid, string machno) {
            object[] results = this.Invoke("Finish", new object[] {
                        tenkeo,
                        mesid,
                        machno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FinishAsync(string tenkeo, string mesid, string machno) {
            this.FinishAsync(tenkeo, mesid, machno, null);
        }
        
        /// <remarks/>
        public void FinishAsync(string tenkeo, string mesid, string machno, object userState) {
            if ((this.FinishOperationCompleted == null)) {
                this.FinishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinishOperationCompleted);
            }
            this.InvokeAsync("Finish", new object[] {
                        tenkeo,
                        mesid,
                        machno}, this.FinishOperationCompleted, userState);
        }
        
        private void OnFinishOperationCompleted(object arg) {
            if ((this.FinishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinishCompleted(this, new FinishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Update(string some, string mesid, string machno) {
            object[] results = this.Invoke("Update", new object[] {
                        some,
                        mesid,
                        machno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(string some, string mesid, string machno) {
            this.UpdateAsync(some, mesid, machno, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(string some, string mesid, string machno, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        some,
                        mesid,
                        machno}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Dieudong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Dieudong(string some, string tenkeo, string loaikeo, string Machno, string ca, string PDA, string usrno) {
            object[] results = this.Invoke("Dieudong", new object[] {
                        some,
                        tenkeo,
                        loaikeo,
                        Machno,
                        ca,
                        PDA,
                        usrno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DieudongAsync(string some, string tenkeo, string loaikeo, string Machno, string ca, string PDA, string usrno) {
            this.DieudongAsync(some, tenkeo, loaikeo, Machno, ca, PDA, usrno, null);
        }
        
        /// <remarks/>
        public void DieudongAsync(string some, string tenkeo, string loaikeo, string Machno, string ca, string PDA, string usrno, object userState) {
            if ((this.DieudongOperationCompleted == null)) {
                this.DieudongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDieudongOperationCompleted);
            }
            this.InvokeAsync("Dieudong", new object[] {
                        some,
                        tenkeo,
                        loaikeo,
                        Machno,
                        ca,
                        PDA,
                        usrno}, this.DieudongOperationCompleted, userState);
        }
        
        private void OnDieudongOperationCompleted(object arg) {
            if ((this.DieudongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DieudongCompleted(this, new DieudongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getBarcode(string mesid) {
            object[] results = this.Invoke("getBarcode", new object[] {
                        mesid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getBarcodeAsync(string mesid) {
            this.getBarcodeAsync(mesid, null);
        }
        
        /// <remarks/>
        public void getBarcodeAsync(string mesid, object userState) {
            if ((this.getBarcodeOperationCompleted == null)) {
                this.getBarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBarcodeOperationCompleted);
            }
            this.InvokeAsync("getBarcode", new object[] {
                        mesid}, this.getBarcodeOperationCompleted, userState);
        }
        
        private void OngetBarcodeOperationCompleted(object arg) {
            if ((this.getBarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBarcodeCompleted(this, new getBarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_PrinterList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_PrinterList() {
            object[] results = this.Invoke("Get_PrinterList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_PrinterListAsync() {
            this.Get_PrinterListAsync(null);
        }
        
        /// <remarks/>
        public void Get_PrinterListAsync(object userState) {
            if ((this.Get_PrinterListOperationCompleted == null)) {
                this.Get_PrinterListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PrinterListOperationCompleted);
            }
            this.InvokeAsync("Get_PrinterList", new object[0], this.Get_PrinterListOperationCompleted, userState);
        }
        
        private void OnGet_PrinterListOperationCompleted(object arg) {
            if ((this.Get_PrinterListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PrinterListCompleted(this, new Get_PrinterListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Barcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Barcode(string mesid, string machno) {
            object[] results = this.Invoke("Get_Barcode", new object[] {
                        mesid,
                        machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_BarcodeAsync(string mesid, string machno) {
            this.Get_BarcodeAsync(mesid, machno, null);
        }
        
        /// <remarks/>
        public void Get_BarcodeAsync(string mesid, string machno, object userState) {
            if ((this.Get_BarcodeOperationCompleted == null)) {
                this.Get_BarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_BarcodeOperationCompleted);
            }
            this.InvokeAsync("Get_Barcode", new object[] {
                        mesid,
                        machno}, this.Get_BarcodeOperationCompleted, userState);
        }
        
        private void OnGet_BarcodeOperationCompleted(object arg) {
            if ((this.Get_BarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_BarcodeCompleted(this, new Get_BarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mesidauto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string mesidauto(string mesid) {
            object[] results = this.Invoke("mesidauto", new object[] {
                        mesid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void mesidautoAsync(string mesid) {
            this.mesidautoAsync(mesid, null);
        }
        
        /// <remarks/>
        public void mesidautoAsync(string mesid, object userState) {
            if ((this.mesidautoOperationCompleted == null)) {
                this.mesidautoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmesidautoOperationCompleted);
            }
            this.InvokeAsync("mesidauto", new object[] {
                        mesid}, this.mesidautoOperationCompleted, userState);
        }
        
        private void OnmesidautoOperationCompleted(object arg) {
            if ((this.mesidautoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mesidautoCompleted(this, new mesidautoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Mesid_list_Inlai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Mesid_list_Inlai(string Machno, string ca) {
            object[] results = this.Invoke("Get_Mesid_list_Inlai", new object[] {
                        Machno,
                        ca});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Mesid_list_InlaiAsync(string Machno, string ca) {
            this.Get_Mesid_list_InlaiAsync(Machno, ca, null);
        }
        
        /// <remarks/>
        public void Get_Mesid_list_InlaiAsync(string Machno, string ca, object userState) {
            if ((this.Get_Mesid_list_InlaiOperationCompleted == null)) {
                this.Get_Mesid_list_InlaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Mesid_list_InlaiOperationCompleted);
            }
            this.InvokeAsync("Get_Mesid_list_Inlai", new object[] {
                        Machno,
                        ca}, this.Get_Mesid_list_InlaiOperationCompleted, userState);
        }
        
        private void OnGet_Mesid_list_InlaiOperationCompleted(object arg) {
            if ((this.Get_Mesid_list_InlaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Mesid_list_InlaiCompleted(this, new Get_Mesid_list_InlaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Mesid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Mesid(string machno, string Tenkeo) {
            object[] results = this.Invoke("Mesid", new object[] {
                        machno,
                        Tenkeo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MesidAsync(string machno, string Tenkeo) {
            this.MesidAsync(machno, Tenkeo, null);
        }
        
        /// <remarks/>
        public void MesidAsync(string machno, string Tenkeo, object userState) {
            if ((this.MesidOperationCompleted == null)) {
                this.MesidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMesidOperationCompleted);
            }
            this.InvokeAsync("Mesid", new object[] {
                        machno,
                        Tenkeo}, this.MesidOperationCompleted, userState);
        }
        
        private void OnMesidOperationCompleted(object arg) {
            if ((this.MesidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MesidCompleted(this, new MesidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_mesid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_mesid(string Machno) {
            object[] results = this.Invoke("get_mesid", new object[] {
                        Machno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_mesidAsync(string Machno) {
            this.get_mesidAsync(Machno, null);
        }
        
        /// <remarks/>
        public void get_mesidAsync(string Machno, object userState) {
            if ((this.get_mesidOperationCompleted == null)) {
                this.get_mesidOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_mesidOperationCompleted);
            }
            this.InvokeAsync("get_mesid", new object[] {
                        Machno}, this.get_mesidOperationCompleted, userState);
        }
        
        private void Onget_mesidOperationCompleted(object arg) {
            if ((this.get_mesidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_mesidCompleted(this, new get_mesidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_mesid_recipe_weght", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_mesid_recipe_weght(string mesid) {
            object[] results = this.Invoke("get_mesid_recipe_weght", new object[] {
                        mesid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_mesid_recipe_weghtAsync(string mesid) {
            this.get_mesid_recipe_weghtAsync(mesid, null);
        }
        
        /// <remarks/>
        public void get_mesid_recipe_weghtAsync(string mesid, object userState) {
            if ((this.get_mesid_recipe_weghtOperationCompleted == null)) {
                this.get_mesid_recipe_weghtOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_mesid_recipe_weghtOperationCompleted);
            }
            this.InvokeAsync("get_mesid_recipe_weght", new object[] {
                        mesid}, this.get_mesid_recipe_weghtOperationCompleted, userState);
        }
        
        private void Onget_mesid_recipe_weghtOperationCompleted(object arg) {
            if ((this.get_mesid_recipe_weghtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_mesid_recipe_weghtCompleted(this, new get_mesid_recipe_weghtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/rubnod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string rubnod(string partno) {
            object[] results = this.Invoke("rubnod", new object[] {
                        partno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rubnodAsync(string partno) {
            this.rubnodAsync(partno, null);
        }
        
        /// <remarks/>
        public void rubnodAsync(string partno, object userState) {
            if ((this.rubnodOperationCompleted == null)) {
                this.rubnodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrubnodOperationCompleted);
            }
            this.InvokeAsync("rubnod", new object[] {
                        partno}, this.rubnodOperationCompleted, userState);
        }
        
        private void OnrubnodOperationCompleted(object arg) {
            if ((this.rubnodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rubnodCompleted(this, new rubnodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkTemVang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] checkTemVang(string barcode) {
            object[] results = this.Invoke("checkTemVang", new object[] {
                        barcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void checkTemVangAsync(string barcode) {
            this.checkTemVangAsync(barcode, null);
        }
        
        /// <remarks/>
        public void checkTemVangAsync(string barcode, object userState) {
            if ((this.checkTemVangOperationCompleted == null)) {
                this.checkTemVangOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckTemVangOperationCompleted);
            }
            this.InvokeAsync("checkTemVang", new object[] {
                        barcode}, this.checkTemVangOperationCompleted, userState);
        }
        
        private void OncheckTemVangOperationCompleted(object arg) {
            if ((this.checkTemVangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkTemVangCompleted(this, new checkTemVangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insIF_Scan2Mes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insIF_Scan2Mes(string barcode, string machine_no) {
            object[] results = this.Invoke("insIF_Scan2Mes", new object[] {
                        barcode,
                        machine_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insIF_Scan2MesAsync(string barcode, string machine_no) {
            this.insIF_Scan2MesAsync(barcode, machine_no, null);
        }
        
        /// <remarks/>
        public void insIF_Scan2MesAsync(string barcode, string machine_no, object userState) {
            if ((this.insIF_Scan2MesOperationCompleted == null)) {
                this.insIF_Scan2MesOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsIF_Scan2MesOperationCompleted);
            }
            this.InvokeAsync("insIF_Scan2Mes", new object[] {
                        barcode,
                        machine_no}, this.insIF_Scan2MesOperationCompleted, userState);
        }
        
        private void OninsIF_Scan2MesOperationCompleted(object arg) {
            if ((this.insIF_Scan2MesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insIF_Scan2MesCompleted(this, new insIF_Scan2MesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadPlanid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LoadPlanid() {
            object[] results = this.Invoke("LoadPlanid", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LoadPlanidAsync() {
            this.LoadPlanidAsync(null);
        }
        
        /// <remarks/>
        public void LoadPlanidAsync(object userState) {
            if ((this.LoadPlanidOperationCompleted == null)) {
                this.LoadPlanidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadPlanidOperationCompleted);
            }
            this.InvokeAsync("LoadPlanid", new object[0], this.LoadPlanidOperationCompleted, userState);
        }
        
        private void OnLoadPlanidOperationCompleted(object arg) {
            if ((this.LoadPlanidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadPlanidCompleted(this, new LoadPlanidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ins_cantay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ins_cantay(string plan_id, string barcode, string recipe_name, string wgt) {
            object[] results = this.Invoke("ins_cantay", new object[] {
                        plan_id,
                        barcode,
                        recipe_name,
                        wgt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ins_cantayAsync(string plan_id, string barcode, string recipe_name, string wgt) {
            this.ins_cantayAsync(plan_id, barcode, recipe_name, wgt, null);
        }
        
        /// <remarks/>
        public void ins_cantayAsync(string plan_id, string barcode, string recipe_name, string wgt, object userState) {
            if ((this.ins_cantayOperationCompleted == null)) {
                this.ins_cantayOperationCompleted = new System.Threading.SendOrPostCallback(this.Onins_cantayOperationCompleted);
            }
            this.InvokeAsync("ins_cantay", new object[] {
                        plan_id,
                        barcode,
                        recipe_name,
                        wgt}, this.ins_cantayOperationCompleted, userState);
        }
        
        private void Onins_cantayOperationCompleted(object arg) {
            if ((this.ins_cantayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ins_cantayCompleted(this, new ins_cantayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Check_mes_pday", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Check_mes_pday(string indate, string intime, string pday) {
            this.Invoke("Check_mes_pday", new object[] {
                        indate,
                        intime,
                        pday});
        }
        
        /// <remarks/>
        public void Check_mes_pdayAsync(string indate, string intime, string pday) {
            this.Check_mes_pdayAsync(indate, intime, pday, null);
        }
        
        /// <remarks/>
        public void Check_mes_pdayAsync(string indate, string intime, string pday, object userState) {
            if ((this.Check_mes_pdayOperationCompleted == null)) {
                this.Check_mes_pdayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_mes_pdayOperationCompleted);
            }
            this.InvokeAsync("Check_mes_pday", new object[] {
                        indate,
                        intime,
                        pday}, this.Check_mes_pdayOperationCompleted, userState);
        }
        
        private void OnCheck_mes_pdayOperationCompleted(object arg) {
            if ((this.Check_mes_pdayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_mes_pdayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Check_barcode_if_scan2mes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Check_barcode_if_scan2mes(string barcode) {
            object[] results = this.Invoke("Check_barcode_if_scan2mes", new object[] {
                        barcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_barcode_if_scan2mesAsync(string barcode) {
            this.Check_barcode_if_scan2mesAsync(barcode, null);
        }
        
        /// <remarks/>
        public void Check_barcode_if_scan2mesAsync(string barcode, object userState) {
            if ((this.Check_barcode_if_scan2mesOperationCompleted == null)) {
                this.Check_barcode_if_scan2mesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_barcode_if_scan2mesOperationCompleted);
            }
            this.InvokeAsync("Check_barcode_if_scan2mes", new object[] {
                        barcode}, this.Check_barcode_if_scan2mesOperationCompleted, userState);
        }
        
        private void OnCheck_barcode_if_scan2mesOperationCompleted(object arg) {
            if ((this.Check_barcode_if_scan2mesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_barcode_if_scan2mesCompleted(this, new Check_barcode_if_scan2mesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Check_palletBB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Check_palletBB(string palletno) {
            object[] results = this.Invoke("Check_palletBB", new object[] {
                        palletno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_palletBBAsync(string palletno) {
            this.Check_palletBBAsync(palletno, null);
        }
        
        /// <remarks/>
        public void Check_palletBBAsync(string palletno, object userState) {
            if ((this.Check_palletBBOperationCompleted == null)) {
                this.Check_palletBBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_palletBBOperationCompleted);
            }
            this.InvokeAsync("Check_palletBB", new object[] {
                        palletno}, this.Check_palletBBOperationCompleted, userState);
        }
        
        private void OnCheck_palletBBOperationCompleted(object arg) {
            if ((this.Check_palletBBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_palletBBCompleted(this, new Check_palletBBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insIF_Scan2Mes_new", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insIF_Scan2Mes_new(string barcode, string machine_no) {
            object[] results = this.Invoke("insIF_Scan2Mes_new", new object[] {
                        barcode,
                        machine_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insIF_Scan2Mes_newAsync(string barcode, string machine_no) {
            this.insIF_Scan2Mes_newAsync(barcode, machine_no, null);
        }
        
        /// <remarks/>
        public void insIF_Scan2Mes_newAsync(string barcode, string machine_no, object userState) {
            if ((this.insIF_Scan2Mes_newOperationCompleted == null)) {
                this.insIF_Scan2Mes_newOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsIF_Scan2Mes_newOperationCompleted);
            }
            this.InvokeAsync("insIF_Scan2Mes_new", new object[] {
                        barcode,
                        machine_no}, this.insIF_Scan2Mes_newOperationCompleted, userState);
        }
        
        private void OninsIF_Scan2Mes_newOperationCompleted(object arg) {
            if ((this.insIF_Scan2Mes_newCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insIF_Scan2Mes_newCompleted(this, new insIF_Scan2Mes_newCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ins_LRweigh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ins_LRweigh(string barcode, string recipe, string may) {
            object[] results = this.Invoke("ins_LRweigh", new object[] {
                        barcode,
                        recipe,
                        may});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ins_LRweighAsync(string barcode, string recipe, string may) {
            this.ins_LRweighAsync(barcode, recipe, may, null);
        }
        
        /// <remarks/>
        public void ins_LRweighAsync(string barcode, string recipe, string may, object userState) {
            if ((this.ins_LRweighOperationCompleted == null)) {
                this.ins_LRweighOperationCompleted = new System.Threading.SendOrPostCallback(this.Onins_LRweighOperationCompleted);
            }
            this.InvokeAsync("ins_LRweigh", new object[] {
                        barcode,
                        recipe,
                        may}, this.ins_LRweighOperationCompleted, userState);
        }
        
        private void Onins_LRweighOperationCompleted(object arg) {
            if ((this.ins_LRweighCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ins_LRweighCompleted(this, new ins_LRweighCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ins_IF_Scan2Mes_new", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ins_IF_Scan2Mes_new(string barcode, string marchno, string partno) {
            object[] results = this.Invoke("ins_IF_Scan2Mes_new", new object[] {
                        barcode,
                        marchno,
                        partno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ins_IF_Scan2Mes_newAsync(string barcode, string marchno, string partno) {
            this.ins_IF_Scan2Mes_newAsync(barcode, marchno, partno, null);
        }
        
        /// <remarks/>
        public void ins_IF_Scan2Mes_newAsync(string barcode, string marchno, string partno, object userState) {
            if ((this.ins_IF_Scan2Mes_newOperationCompleted == null)) {
                this.ins_IF_Scan2Mes_newOperationCompleted = new System.Threading.SendOrPostCallback(this.Onins_IF_Scan2Mes_newOperationCompleted);
            }
            this.InvokeAsync("ins_IF_Scan2Mes_new", new object[] {
                        barcode,
                        marchno,
                        partno}, this.ins_IF_Scan2Mes_newOperationCompleted, userState);
        }
        
        private void Onins_IF_Scan2Mes_newOperationCompleted(object arg) {
            if ((this.ins_IF_Scan2Mes_newCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ins_IF_Scan2Mes_newCompleted(this, new ins_IF_Scan2Mes_newCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sanluong_daquet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] sanluong_daquet(string barcode, string marchno, string partno) {
            object[] results = this.Invoke("sanluong_daquet", new object[] {
                        barcode,
                        marchno,
                        partno});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sanluong_daquetAsync(string barcode, string marchno, string partno) {
            this.sanluong_daquetAsync(barcode, marchno, partno, null);
        }
        
        /// <remarks/>
        public void sanluong_daquetAsync(string barcode, string marchno, string partno, object userState) {
            if ((this.sanluong_daquetOperationCompleted == null)) {
                this.sanluong_daquetOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsanluong_daquetOperationCompleted);
            }
            this.InvokeAsync("sanluong_daquet", new object[] {
                        barcode,
                        marchno,
                        partno}, this.sanluong_daquetOperationCompleted, userState);
        }
        
        private void Onsanluong_daquetOperationCompleted(object arg) {
            if ((this.sanluong_daquetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sanluong_daquetCompleted(this, new sanluong_daquetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sv_hoachat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sv_hoachat(
                    string may, 
                    string chat, 
                    string some, 
                    string solo, 
                    string thoigian, 
                    string hansd, 
                    string nguoilam, 
                    string TGKT, 
                    string real_num, 
                    string plan_id, 
                    string tenbieu, 
                    string tenbieu1, 
                    string tenbieu2, 
                    string tenbieu3, 
                    string pathFile, 
                    string filename) {
            object[] results = this.Invoke("sv_hoachat", new object[] {
                        may,
                        chat,
                        some,
                        solo,
                        thoigian,
                        hansd,
                        nguoilam,
                        TGKT,
                        real_num,
                        plan_id,
                        tenbieu,
                        tenbieu1,
                        tenbieu2,
                        tenbieu3,
                        pathFile,
                        filename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sv_hoachatAsync(
                    string may, 
                    string chat, 
                    string some, 
                    string solo, 
                    string thoigian, 
                    string hansd, 
                    string nguoilam, 
                    string TGKT, 
                    string real_num, 
                    string plan_id, 
                    string tenbieu, 
                    string tenbieu1, 
                    string tenbieu2, 
                    string tenbieu3, 
                    string pathFile, 
                    string filename) {
            this.sv_hoachatAsync(may, chat, some, solo, thoigian, hansd, nguoilam, TGKT, real_num, plan_id, tenbieu, tenbieu1, tenbieu2, tenbieu3, pathFile, filename, null);
        }
        
        /// <remarks/>
        public void sv_hoachatAsync(
                    string may, 
                    string chat, 
                    string some, 
                    string solo, 
                    string thoigian, 
                    string hansd, 
                    string nguoilam, 
                    string TGKT, 
                    string real_num, 
                    string plan_id, 
                    string tenbieu, 
                    string tenbieu1, 
                    string tenbieu2, 
                    string tenbieu3, 
                    string pathFile, 
                    string filename, 
                    object userState) {
            if ((this.sv_hoachatOperationCompleted == null)) {
                this.sv_hoachatOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsv_hoachatOperationCompleted);
            }
            this.InvokeAsync("sv_hoachat", new object[] {
                        may,
                        chat,
                        some,
                        solo,
                        thoigian,
                        hansd,
                        nguoilam,
                        TGKT,
                        real_num,
                        plan_id,
                        tenbieu,
                        tenbieu1,
                        tenbieu2,
                        tenbieu3,
                        pathFile,
                        filename}, this.sv_hoachatOperationCompleted, userState);
        }
        
        private void Onsv_hoachatOperationCompleted(object arg) {
            if ((this.sv_hoachatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sv_hoachatCompleted(this, new sv_hoachatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_Mesid_listCompletedEventHandler(object sender, Get_Mesid_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Mesid_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Mesid_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetRecipe_nameDuoiCompletedEventHandler(object sender, GetRecipe_nameDuoiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecipe_nameDuoiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecipe_nameDuoiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_shiftCompletedEventHandler(object sender, Get_shiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_shiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_shiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Print_BBCompletedEventHandler(object sender, Print_BBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Print_BBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Print_BBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Print_BB_AgainCompletedEventHandler(object sender, Print_BB_AgainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Print_BB_AgainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Print_BB_AgainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FinishCompletedEventHandler(object sender, FinishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FinishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FinishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DieudongCompletedEventHandler(object sender, DieudongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DieudongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DieudongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBarcodeCompletedEventHandler(object sender, getBarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_PrinterListCompletedEventHandler(object sender, Get_PrinterListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PrinterListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PrinterListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_BarcodeCompletedEventHandler(object sender, Get_BarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_BarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_BarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mesidautoCompletedEventHandler(object sender, mesidautoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mesidautoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mesidautoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_Mesid_list_InlaiCompletedEventHandler(object sender, Get_Mesid_list_InlaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Mesid_list_InlaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Mesid_list_InlaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MesidCompletedEventHandler(object sender, MesidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MesidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MesidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_mesidCompletedEventHandler(object sender, get_mesidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_mesidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_mesidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_mesid_recipe_weghtCompletedEventHandler(object sender, get_mesid_recipe_weghtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_mesid_recipe_weghtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_mesid_recipe_weghtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void rubnodCompletedEventHandler(object sender, rubnodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rubnodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rubnodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkTemVangCompletedEventHandler(object sender, checkTemVangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkTemVangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkTemVangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insIF_Scan2MesCompletedEventHandler(object sender, insIF_Scan2MesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insIF_Scan2MesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insIF_Scan2MesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoadPlanidCompletedEventHandler(object sender, LoadPlanidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadPlanidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadPlanidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ins_cantayCompletedEventHandler(object sender, ins_cantayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ins_cantayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ins_cantayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Check_mes_pdayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Check_barcode_if_scan2mesCompletedEventHandler(object sender, Check_barcode_if_scan2mesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_barcode_if_scan2mesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_barcode_if_scan2mesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Check_palletBBCompletedEventHandler(object sender, Check_palletBBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_palletBBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_palletBBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insIF_Scan2Mes_newCompletedEventHandler(object sender, insIF_Scan2Mes_newCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insIF_Scan2Mes_newCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insIF_Scan2Mes_newCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ins_LRweighCompletedEventHandler(object sender, ins_LRweighCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ins_LRweighCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ins_LRweighCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ins_IF_Scan2Mes_newCompletedEventHandler(object sender, ins_IF_Scan2Mes_newCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ins_IF_Scan2Mes_newCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ins_IF_Scan2Mes_newCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sanluong_daquetCompletedEventHandler(object sender, sanluong_daquetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sanluong_daquetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sanluong_daquetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sv_hoachatCompletedEventHandler(object sender, sv_hoachatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sv_hoachatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sv_hoachatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591